// ---- ANTI ROBO DEL GM por Rasis ----

//==============================================================================
#define GAMEMODE	"D79 v0.1 [BETA]"
#define GAMEMODE_USE_VERSION	"v0.1 [BETA]"
#define MAP_NAME	"Los Santos"
#define SERVER_NAME	"Distrito 79 *Role Play* [d-79.es]"
#define WEBSITE	"www.d-79.es"
#define VERSION	" D79 HOST"
#define LAST_UPDATE	"28/01/2010"
#define DEVELOPER	" "
#define PASSWORD	" "
#define SCRIPT_LINES 	67786

//==============================================================================
#define PICKUP_RANGE 50
#define MAX_S_PICKUPS 400
#define MAX_ZONE_NAME 28
#define MAX_SPAWN_ATTEMPTS 4
#define txtcost 15
#define PRODUCT_PRICE 10
//==============================================================================
#define BUSINESS_TYPES "1: Restaurante - 2: Telefono - 3: 24-7 - 4: Ammu-nation - 5: Anuncios - 6: Tienda de Ropa - 7. Bar/Club"
#define BUSINESS_TYPES2 " "
//==============================================================================
#define MAX_CCTVS 100
#define MAX_CCTVMENUS 10
//==============================================================================
#define COLOR_BRIGHTRED 0xFF0000AA
#define COLOR_DARKBLUE 0x3399FFAA
#define COLOR_GRAD1 0xB4B5B7FF
#define COLOR_MAFIA 0x212121AA
#define COLOR_GRAD5 0xE3E3E3FF
#define TEAM_ORANGE_COLOR 0xFF830000
#define TEAM_AZTECAS_COLOR 0x01FCFFC8
#define COLOR_LSPD 0x0000FFAA
#define COLOR_GRAD2 0xBFC0C2FF
#define COLOR_LEAVE 0xBBBBBBAA
#define COLOR_CIVILIAN 0xFFFFFFFF
#define COLOR_LOCALMSG 0xEC5413AA
#define COLOR_ADMINCMD 0x007E96F6
#define COLOR_FADE1 0xE6E6E6E6
#define COLOR_FADE2 0xC8C8C8C8
#define COLOR_FADE3 0xAAAAAAAA
#define COLOR_ALLDEPT 0xFF8282AA
#define COLOR_FADE4 0x8C8C8C8C
#define COLOR_FADE5 0x6E6E6E6E
#define COLOR_ADMINDUTY 0x007E96F6
#define COLOR_NOTLOGGED 0x00000000
#define COLOR_GRAD1 0xB4B5B7FF
#define COLOR_GRAD2 0xBFC0C2FF
#define COLOR_GRAD3 0xCBCCCEFF
#define COLOR_GRAD4 0xD8D8D8FF
#define COLOR_GRAD5 0xE3E3E3FF
#define COLOR_GRAD6 0xF0F0F0FF
#define COLOR_YELLOW2 0xF5DEB3AA
#define COLOR_WHITE 0xFFFFFFAA
#define COLOR_LIGHTGREEN 0x9ACD32AA
#define COLOR_PURPLE 0xC2A2DAAA
#define COLOR_GREY 0xAFAFAFAA
#define COLOR_RED 0xA10000AA
#define COLOR_LIGHTRED 0xFF6347AA
#define COLOR_YELLOW 0xFFFF00AA
#define COLOR_CORAL 0xFF7F50AA
#define COLOR_LIGHTBLUE 0x33CCFFAA
#define COLOR_GREEN 0x33AA33AA
#define COLOR_LIGHTGREEN 0x9ACD32AA
#define COLOR_NEWS 0xFFA500AA
#define COLOR_NEWOOC 0x0080FFAA
#define COLOR_BLACK 0x000000AA
#define LIGHTGREEN 			0x38FF06FF
#define ADMIN_RED 			0xFB0000FF
#define SITE                "www.d-79.es"
#define SOUND_MUSIC1 	                        1187
#define SOUND_OFF                              	1184
#define DIALOGID2 1888
//ANIM---------------
#define negro 0x0E0E0EFF
#define verde 0x47E263FF
#define GREEN 0x21DD00FF
#define RED 0xE60000FF
#define ADMIN_RED 0xFB0000FF
#define YELLOW 0xFFFF00FF
#define ORANGE 0xF97804FF
#define LIGHTRED 0xFF8080FF
#define LIGHTBLUE 0x00C2ECFF
#define PURPLE 0xB360FDFF
#define PLAYER_COLOR 0xFFFFFFFF
#define BLUE 0x1229FAFF
#define LIGHTGREEN 0x38FF06FF
#define DARKPINK 0xE100E1FF
#define DARKGREEN 0x008040FF
#define ANNOUNCEMENT 0x6AF7E1FF
#define COLOR_SYSTEM 0xEFEFF7AA
#define GREY 0xCECECEFF
#define PINK 0xD52DFFFF
#define DARKGREY    0x626262FF
#define AQUAGREEN   0x03D687FF
#define NICESKY 0x99FFFFAA
#define WHITE                   0xFFFFFFFF
#define AZUL 0x76BDF8FF
#define SPECIAL_ACTION_PISSING      68
//==============================================================================
#define ResetMoneyBar ResetPlayerMoney
#define UpdateMoneyBar GivePlayerMoney
#define GasMax 100